/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package cz.vondr.pact.provider

import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test

class LibraryTest {
    
    @Test
    fun `SomeLibraryMethod returns true`() {
        val classUnderTest = Library()
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'")
    }
}
